name: "Build MediaWiki Development Environment Daily"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: "Setup Docker Buildx"
        uses: docker/setup-buildx-action@v1
      
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          
      - name: "Build and push mediawiki-dev-buster container"
        uses: docker/build-push-action@v2
        with:
          context: ./mediawiki-dev/buster
          file: ./mediawiki-dev/buster/Dockerfile
          push: true
          tags: |
            ghcr.io/innereq/containers/mediawiki-dev/buster:latest

      - name: "Build and push mediawiki-dev-buster-php73 container"
        uses: docker/build-push-action@v2
        with:
          context: ./mediawiki-dev/buster-php73
          file: ./mediawiki-dev/buster-php73/Dockerfile
          push: true
          tags: |
            ghcr.io/innereq/containers/mediawiki-dev/buster-php73:latest

      - name: "Build and push mediawiki-dev-buster-php73-jobrunner container"
        uses: docker/build-push-action@v2
        with:
          context: ./mediawiki-dev/buster-php73-jobrunner
          file: ./mediawiki-dev/buster-php73-jobrunner/Dockerfile
          push: true
          tags: |
            ghcr.io/innereq/containers/mediawiki-dev/buster-php73-jobrunner:latest