name: "Build MovieNight Daily"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
         repository: zorchenhimer/MovieNight

      - name: "Build and push MovieNight container"
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          repository: innereq/containers/movienight
          tags: latest